GET http://localhost:8080/accounts?page_id=1&page_size=5
Accept: application/json

###
POST http://localhost:8080/accounts/
Content-Type: application/json

{
  "owner": "New Account Owner",
  "currency": "USD"
}

###
GET http://localhost:8080/accounts/1
Content-Type: application/json

### Create a new transaction
POST http://localhost:8080/transfers/
Content-Type: application/json

{
  "from_account_id": 1,
  "to_account_id": 2,
  "amount": 100,
  "currency": "USD"
}

### CreateUser
POST http://localhost:8080/users/
Content-Type: application/json

{
  "username": "NewUser2",
  "full_name": "New User",
  "password": "123456",
  "email": "test2@gmail.com"

}

### Login
POST http://localhost:8080/users/login/
Content-Type: application/json

{
   "username": "NewUser2",
    "password": "123456"
}

